<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MiddleChildrenQuestionnaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // middle children
        $middles = [
            [
                'id' => 18,
                'reference_number' => 'AO 1.a',
                'questionnaire_tree_id' => 1,
                'name' => 'LSWDO\'s Vision, Mission and Goals',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'reference_number' => 'AO 1.b',
                'questionnaire_tree_id' => 1,
                'name' => 'LSWDO Manual of Operations',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'reference_number' => 'AO 1.c',
                'questionnaire_tree_id' => 1,
                'name' => 'Organizational and Operational Structure',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'reference_number' => 'AO 2.a',
                'questionnaire_tree_id' => 1,
                'name' => 'Registered Social Worker as Head of LSWDO',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'reference_number' => 'AO 2.b',
                'questionnaire_tree_id' => 1,
                'name' => 'Technical staff for program implementation',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'reference_number' => 'AO 2.c',
                'questionnaire_tree_id' => 1,
                'name' => 'Registered social worker as case manager',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'reference_number' => 'AO 2.d',
                'questionnaire_tree_id' => 1,
                'name' => 'Administrative staff',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'reference_number' => 'AO 2.e',
                'questionnaire_tree_id' => 1,
                'name' => 'Pre-Marriage Orientation and Counseling Team',
                'description' => 'NOTE: Not applicable to PSWDOs',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'reference_number' => 'AO 2.f',
                'questionnaire_tree_id' => 1,
                'name' => 'Accredited Social Worker Managing Court Cases',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'reference_number' => 'AO 2.g',
                'questionnaire_tree_id' => 1,
                'name' => 'Training and Development',
                'description' => '',
                'weight' => 7,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 28,
                'reference_number' => 'AO 2.h',
                'questionnaire_tree_id' => 1,
                'name' => 'Performance Appraisal System',
                'description' => '',
                'weight' => 8,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 29,
                'reference_number' => 'AO 2.i',
                'questionnaire_tree_id' => 1,
                'name' => 'Compensation System',
                'description' => '',
                'weight' => 9,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 30,
                'reference_number' => 'AO 2.j',
                'questionnaire_tree_id' => 1,
                'name' => 'Benefits for Public Social Workers',
                'description' => '',
                'weight' => 10,
                'user_id' => 1,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 31,
                'reference_number' => 'AO 3.a',
                'questionnaire_tree_id' => 1,
                'name' => 'Financial Management System',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 32,
                'reference_number' => 'AO 3.b',
                'questionnaire_tree_id' => 1,
                'name' => 'Budget Allocation for SWD Sectors',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 33,
                'reference_number' => 'AO 3.c',
                'questionnaire_tree_id' => 1,
                'name' => 'SWD Budget Utilization',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 34,
                'reference_number' => 'AO 3.d',
                'questionnaire_tree_id' => 1,
                'name' => 'Management of Donations',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 35,
                'reference_number' => 'AO 3.e',
                'questionnaire_tree_id' => 1,
                'name' => 'Resource Augmentation to component LGUs and/ or NGOs',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 6,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 36,
                'reference_number' => 'AO 4.a',
                'questionnaire_tree_id' => 1,
                'name' => 'Information Management System (IT Equipment)',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 37,
                'reference_number' => 'AO 4.b',
                'questionnaire_tree_id' => 1,
                'name' => 'Information Management System ((Info System)',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 38,
                'reference_number' => 'AO 4.c',
                'questionnaire_tree_id' => 1,
                'name' => 'Records Management',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 39,
                'reference_number' => 'AO 4.d',
                'questionnaire_tree_id' => 1,
                'name' => 'Physical Structure',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 40,
                'reference_number' => 'AO 4.e',
                'questionnaire_tree_id' => 1,
                'name' => 'Means of Communication',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 41,
                'reference_number' => 'AO 4.f',
                'questionnaire_tree_id' => 1,
                'name' => 'First Aid and Emergency Personnel',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 42,
                'reference_number' => 'PM 1.a',
                'questionnaire_tree_id' => 1,
                'name' => 'Use of Social Protection (SP) Handbook and SP Vulnerability and Adaptation Manual (SP VAM)',
                'description' => 'NOTE: <ol> <li>a. Not applicable to PSWDOs</li> <li>b. Indicate "Not Applicable" for 2022 SDC Assessment</li>',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 43,
                'reference_number' => 'PM 1.b',
                'questionnaire_tree_id' => 1,
                'name' => 'Social Protection and Development Report (SPDR)',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 44,
                'reference_number' => 'PM 1.c',
                'questionnaire_tree_id' => 1,
                'name' => 'Social Development Plans integrated in the CDP and LDIP',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 45,
                'reference_number' => 'PM 2.a1',
                'questionnaire_tree_id' => 1,
                'name' => 'Identification of at risk and vulnerable families',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 46,
                'reference_number' => 'PM 2.a2',
                'questionnaire_tree_id' => 1,
                'name' => 'Conduct of Capability Building Activities',
                'description' => '<ul><li>Camp management</li><li>Quick Response Team (QRT)</li><li>Relief operations</li><li>Volunteers</li><li>Women and child-friendly spaces</li><li>Psychosocial support</li></ul>',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 47,
                'reference_number' => 'PM 2.a3',
                'questionnaire_tree_id' => 1,
                'name' => 'Prepositioning of relief assistance',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 48,
                'reference_number' => 'PM 2.a4',
                'questionnaire_tree_id' => 1,
                'name' => 'Resource Mapping',
                'description' => '<ul><li>Volunteers</li><li>Evacuation</li><li>Facilities that can be tapped/ used during disaster</li></ul>',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 49,
                'reference_number' => 'PM 2.a5',
                'questionnaire_tree_id' => 1,
                'name' => 'Volunteer management',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 50,
                'reference_number' => 'PM 2.a6',
                'questionnaire_tree_id' => 1,
                'name' => 'Disaster Response',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 51,
                'reference_number' => 'PM 2.a7',
                'questionnaire_tree_id' => 1,
                'name' => 'Early Recovery and Rehabilitation',
                'description' => '',
                'weight' => 7,
                'user_id' => 1,
                'parent_id' => 9,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 52,
                'reference_number' => 'PM 2.b1',
                'questionnaire_tree_id' => 1,
                'name' => 'Former Rebels (if applicable)',
                'description' => 'NOTE: Not applicable to CSWDOs and MSWDOs',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 53,
                'reference_number' => 'PM 2.b2',
                'questionnaire_tree_id' => 1,
                'name' => 'Family and Community Welfare',
                'description' => 'NOTE: Not applicable to PSWDO',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 54,
                'reference_number' => 'PM 2.b3',
                'questionnaire_tree_id' => 1,
                'name' => 'Women Welfare',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 55,
                'reference_number' => 'PM 2.b4',
                'questionnaire_tree_id' => 1,
                'name' => 'Children and Youth Welfare',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 56,
                'reference_number' => 'PM 2.b5',
                'questionnaire_tree_id' => 1,
                'name' => 'Senior Citizens Welfare',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 57,
                'reference_number' => 'PM 2.b6',
                'questionnaire_tree_id' => 1,
                'name' => 'Persons with Disability Welfare',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 58,
                'reference_number' => 'PM 2.b7',
                'questionnaire_tree_id' => 1,
                'name' => 'Assistance to Individuals in Crisis Situation (AICS)',
                'description' => '',
                'weight' => 7,
                'user_id' => 1,
                'parent_id' => 10,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 59,
                'reference_number' => 'PM 3a',
                'questionnaire_tree_id' => 1,
                'name' => 'Conduct of LSWDO Staff Meeting',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 11,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 60,
                'reference_number' => 'PM 3b',
                'questionnaire_tree_id' => 1,
                'name' => 'Reporting of Accomplishments',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 11,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 61,
                'reference_number' => 'PM 3c',
                'questionnaire_tree_id' => 1,
                'name' => 'Meeting with C/MSWDOs',
                'description' => 'NOTE: Not applicable to C/MSWDOs',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 11,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 62,
                'reference_number' => 'PM 4a',
                'questionnaire_tree_id' => 1,
                'name' => 'Client Assessment',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 63,
                'reference_number' => 'PM 4b',
                'questionnaire_tree_id' => 1,
                'name' => 'Implementation',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 64,
                'reference_number' => 'PM 4c',
                'questionnaire_tree_id' => 1,
                'name' => 'Evaluation/ Case Conference',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 65,
                'reference_number' => 'PM 4d',
                'questionnaire_tree_id' => 1,
                'name' => 'Referral System',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 66,
                'reference_number' => 'PM 4e',
                'questionnaire_tree_id' => 1,
                'name' => 'Database of clients',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 67,
                'reference_number' => 'PM 4f',
                'questionnaire_tree_id' => 1,
                'name' => 'Case load',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 12,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 68,
                'reference_number' => 'PM 5a',
                'questionnaire_tree_id' => 1,
                'name' => 'Residential Care Facility (If applicable)',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 13,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 69,
                'reference_number' => 'PM 5b',
                'questionnaire_tree_id' => 1,
                'name' => 'Community-Based Center',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 13,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 70,
                'reference_number' => 'IM 2a',
                'questionnaire_tree_id' => 1,
                'name' => 'Establishment of LCAT-VAWC',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 71,
                'reference_number' => 'IM 2b',
                'questionnaire_tree_id' => 1,
                'name' => 'Accomplishment Reports',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 72,
                'reference_number' => 'IM 2c',
                'questionnaire_tree_id' => 1,
                'name' => 'Conduct of LCAT-VAWC Meetings',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 73,
                'reference_number' => 'IM 2d',
                'questionnaire_tree_id' => 1,
                'name' => 'LCAT-VAWC Work and Financial Plan',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 74,
                'reference_number' => 'IM 2e',
                'questionnaire_tree_id' => 1,
                'name' => 'Policy Establishing Barangay VAWC Desks',
                'description' => 'NOTE: Not applicable to PSWDO',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 75,
                'reference_number' => 'IM 2f',
                'questionnaire_tree_id' => 1,
                'name' => 'Percentage of Barangays with VAWC Desks',
                'description' => 'NOTE: Not applicable to PSWDO',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 76,
                'reference_number' => 'IM 2g',
                'questionnaire_tree_id' => 1,
                'name' => 'Barangay VAWC Reports',
                'description' => 'NOTE: Not applicable to PSWDO',
                'weight' => 7,
                'user_id' => 1,
                'parent_id' => 14,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 77,
                'reference_number' => 'IM 1A',
                'questionnaire_tree_id' => 1,
                'name' => 'Functionality of LCPC',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 78,
                'reference_number' => 'IM 1b',
                'questionnaire_tree_id' => 1,
                'name' => 'Conduct of LCPC Meetings',
                'description' => '',
                'weight' => 2,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 79,
                'reference_number' => 'IM 1c',
                'questionnaire_tree_id' => 1,
                'name' => 'LCPC Work and Financial Plan',
                'description' => '',
                'weight' => 3,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 80,
                'reference_number' => 'IM 1d',
                'questionnaire_tree_id' => 1,
                'name' => 'LCPC Accomplishment Report',
                'description' => '',
                'weight' => 4,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 81,
                'reference_number' => 'IM 1e',
                'questionnaire_tree_id' => 1,
                'name' => 'Local Code for Children',
                'description' => '',
                'weight' => 5,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 82,
                'reference_number' => 'IM 1f',
                'questionnaire_tree_id' => 1,
                'name' => 'Local Juvenile Intervention Program',
                'description' => '',
                'weight' => 6,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 83,
                'reference_number' => 'IM 1g',
                'questionnaire_tree_id' => 1,
                'name' => 'Child Development Centers and Child Development Workers',
                'description' => '',
                'weight' => 7,
                'user_id' => 1,
                'parent_id' => 15,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id' => 84,
                'reference_number' => 'IM 2a',
                'questionnaire_tree_id' => 1,
                'name' => 'Membership to Various Committees',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 16,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 85,
                'reference_number' => 'IM 4a',
                'questionnaire_tree_id' => 1,
                'name' => 'Technical Assistance and Resource Augmentation to CSOs',
                'description' => '',
                'weight' => 1,
                'user_id' => 1,
                'parent_id' => 17,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];
        DB::table('questionnaires')->insert($middles);
    }
}
