<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TransactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('transactions')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $transactions = [
            // Upcoming
            [
                'queue_number' => 14,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 15,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 16,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 17,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 18,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 19,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 20,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 21,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 22,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 23,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 24,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 25,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 26,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Priority
            [
                'queue_number' => 14,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 15,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 16,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 17,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 18,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 19,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 20,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 21,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 22,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 23,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 24,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 25,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 26,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Pending
            [
                'queue_number' => 1,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 2,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 3,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 4,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 5,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 6,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 7,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 8,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 9,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 10,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 11,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 12,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 13,
                'client_type' => 'regular',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],







            [
                'queue_number' => 1,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 2,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 3,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 4,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 5,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 6,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 7,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 8,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 9,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 10,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 11,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 12,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'queue_number' => 13,
                'client_type' => 'priority',
                'step_id' => 1,
                'window_id' => null,
                'section_id' => 14,
                'queue_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],








            // CIS clients queues
            [
                'queue_number' => 1,
                'client_type' => 'priority',
                'step_id' => 5,
                'window_id' => 5,
                'section_id' => 15,
                'queue_status' => 'waiting',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],





        ];



        DB::table('transactions')->insert($transactions);
    }
}
