<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $users = [
            [
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'email' => env('ADMIN_EMAIL', 'superadmin@admin.com'),
                'position' => 'Super Admin',
                'section_id' => null,
                'user_type' => 0,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'IDScan',
                'last_name' => 'User',
                'email' => 'idscan@dswd.gov.ph',
                'position' => null,
                'section_id' => null,
                'user_type' => 2,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'General',
                'last_name' => 'PACD',
                'email' => env('ADMIN_EMAIL', 'genpacd@dswd.gov.ph'),
                'position' => 'SWAID',
                'section_id' => null,
                'user_type' => 3,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ========== CBSS ACCOUNTS ==========
            [
                'first_name' => 'CBSS',
                'last_name' => 'Admin',
                'email' => env('ADMIN_EMAIL', 'cbss@admin.com'),
                'position' => 'Admin',
                'section_id' => 14,
                'user_type' => 1,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CBSS USER
            [
                'first_name' => 'CBSS',
                'last_name' => 'User',
                'email' => 'usercbss@dswd.gov.ph', // change as needed
                'position' => 'SWOII', // optional
                'section_id' => 14,
                'user_type' => 5,
                'assigned_category' => null,
                'step_id' => 14,
                'window_id' => 14,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CBSS DISPLAY
            [
                'first_name' => 'CBSS',
                'last_name' => 'Display',
                'email' => 'displaycbss@dswd.gov.ph',
                'position' => 'SWOII',
                'section_id' => 14,
                'user_type' => 6,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ========== CIS ACCOUNTS ==========
            // CIS ADMIN
            [
                'first_name' => 'CIS',
                'last_name' => 'Admin',
                'email' => env('ADMIN_EMAIL', 'cis@admin.com'),
                'position' => 'Admin',
                'section_id' => 15,
                'user_type' => 1,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS PACD
            [
                'first_name' => 'CIS',
                'last_name' => 'PACD',
                'email' => env('ADMIN_EMAIL', 'cispacd@dswd.gov.ph'),
                'position' => 'SWAID',
                'section_id' => 15,
                'user_type' => 3,
                'assigned_category' => null,
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS PREASSESSMENT
            [
                'first_name' => 'Preasssess',
                'last_name' => 'Regular',
                'email' => 'preassessregu@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'regular',
                'step_id' => 15,
                'window_id' => 15,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Preasssess',
                'last_name' => 'Priority',
                'email' => 'preassessprio@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'priority',
                'step_id' => 15,
                'window_id' => 15,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS ENCODER
            [
                'first_name' => 'Encoding',
                'last_name' => 'Regular',
                'email' => 'encodingregu1@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'regular',
                'step_id' => 16,
                'window_id' => 16,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Encoding',
                'last_name' => 'Regular',
                'email' => 'encodingregu2@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'regular',
                'step_id' => 16,
                'window_id' => 17,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Encoding',
                'last_name' => 'Priority',
                'email' => 'encodingprio1@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'priority',
                'step_id' => 16,
                'window_id' => 16,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS ASSESSMENT
            [
                'first_name' => 'Assessment',
                'last_name' => 'Window1',
                'email' => 'assessment1@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 17,
                'window_id' => 18,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Assessment',
                'last_name' => 'Window2',
                'email' => 'assessment2@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 17,
                'window_id' => 19,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Assessment',
                'last_name' => 'Window3',
                'email' => 'assessment3@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 17,
                'window_id' => 20,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS RELEASING
            [
                'first_name' => 'Releasing',
                'last_name' => 'Window1',
                'email' => 'releasing1@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 18,
                'window_id' => 21,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Releasing',
                'last_name' => 'Window2',
                'email' => 'releasing2@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 18,
                'window_id' => 22,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Releasing',
                'last_name' => 'Window3',
                'email' => 'releasing3@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 5,
                'assigned_category' => 'both',
                'step_id' => 18,
                'window_id' => 23,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CIS DISPLAY
            [
                'first_name' => 'Display',
                'last_name' => 'Regular',
                'email' => 'cisdisplayregu@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 6,
                'assigned_category' => 'regular',
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Display',
                'last_name' => 'Priority',
                'email' => 'cisdisplayprio@dswd.gov.ph',
                'position' => 'None',
                'section_id' => 15,
                'user_type' => 6,
                'assigned_category' => 'priority',
                'step_id' => null,
                'window_id' => null,
                'status' => 1,
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password'),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],




        ];

        DB::table('users')->insert($users);
    }
}
